#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
frontend_dir=${1:-"$repo_dir/../hop-rs-frontend"}
asset_dir=$repo_dir/htdocs/hop/assets
panel_dir=$repo_dir/root/usr/share/hop/panel
panel_marker=$repo_dir/root/usr/share/hop/panel.version

test -f "$frontend_dir/package.json"
grep -Fq '"name": "hop-rs-frontend"' "$frontend_dir/package.json"
package_version=$(sed -n 's/^PKG_VERSION:=//p' "$repo_dir/Makefile")
frontend_version=$(node -e '
const fs = require("node:fs");
const packageJson = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
process.stdout.write(packageJson.version);
' "$frontend_dir/package.json")
test -n "$package_version"
test "$frontend_version" = "$package_version"

npm --prefix "$frontend_dir" run build:openwrt

test -f "$frontend_dir/dist/index.html"
test -d "$frontend_dir/dist/assets"

mkdir -p "$asset_dir" "$panel_dir"
find "$asset_dir" -mindepth 1 -maxdepth 1 -type f -delete
cp -p "$frontend_dir"/dist/assets/* "$asset_dir"/
cp -p "$frontend_dir/dist/index.html" "$panel_dir/index.html"
printf '%s\n' \
	'# Generated by scripts/sync-frontend.sh; do not edit.' \
	'source=hop-rs-frontend' \
	"version=$frontend_version" >"$panel_marker"

printf 'Synced Hop OpenWrt panel from %s\n' "$frontend_dir"
