#!/bin/sh /etc/rc.common
# rc.common consumes globals and provides local.
# shellcheck disable=SC2034,SC3043

USE_PROCD=1
START=95
STOP=10

start_service() {
	local enabled config_path stdout stderr

	config_load hop
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get config_path main config_path /etc/hop/config.toml
	config_get_bool stdout main log_stdout 1
	config_get_bool stderr main log_stderr 1

	mkdir -p /var/lib/hop
	chown hop:hop /var/lib/hop

	procd_open_instance hop
	procd_set_param command /usr/bin/hop-server --config "$config_path" serve
	procd_set_param user hop
	procd_set_param respawn 3600 5 5
	procd_set_param limits nofile="4096 4096"
	procd_set_param file "$config_path"
	procd_set_param stdout "$stdout"
	procd_set_param stderr "$stderr"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger hop
}

reload_service() {
	stop
	start
}
